const kanjiList = [
  { kanji: "一", meaning: "one", onyomi: "イチ, イツ", kunyomi: "ひと-つ" },
  { kanji: "二", meaning: "two", onyomi: "ニ, ジ", kunyomi: "ふた-つ" },
  { kanji: "三", meaning: "three", onyomi: "サン", kunyomi: "みっ-つ" },
  { kanji: "四", meaning: "four", onyomi: "シ", kunyomi: "よん, よっ-つ, よ" },
  { kanji: "五", meaning: "five", onyomi: "ゴ", kunyomi: "いつ-つ" },
  { kanji: "六", meaning: "six", onyomi: "ロク, リク", kunyomi: "むっ-つ, むい" },
  { kanji: "七", meaning: "seven", onyomi: "シチ", kunyomi: "なな-つ, なの" },
  { kanji: "八", meaning: "eight", onyomi: "ハチ", kunyomi: "やっ-つ, よう" },
  { kanji: "九", meaning: "nine", onyomi: "キュウ, ク", kunyomi: "ここの-つ" },
  { kanji: "十", meaning: "ten", onyomi: "ジュウ, ジッ", kunyomi: "とお, と" },
  { kanji: "百", meaning: "hundred", onyomi: "ヒャク", kunyomi: "" },
  { kanji: "千", meaning: "thousand", onyomi: "セン", kunyomi: "" },
  { kanji: "円", meaning: "yen, circle", onyomi: "エン", kunyomi: "まる.い" },
  { kanji: "日", meaning: "day, sun", onyomi: "ニチ, ジツ", kunyomi: "ひ, -び, -か" },
  { kanji: "月", meaning: "month, moon", onyomi: "ゲツ, ガツ", kunyomi: "つき" },
  { kanji: "火", meaning: "fire", onyomi: "カ", kunyomi: "ひ, -び, ほ-" },
  { kanji: "水", meaning: "water", onyomi: "スイ", kunyomi: "みず" },
  { kanji: "木", meaning: "tree, wood", onyomi: "ボク, モク", kunyomi: "き, こ-" },
  { kanji: "金", meaning: "gold, money", onyomi: "キン, コン", kunyomi: "かね, かな-" },
  { kanji: "土", meaning: "earth, soil", onyomi: "ド, ト", kunyomi: "つち" },
  { kanji: "曜", meaning: "weekday", onyomi: "ヨウ", kunyomi: "" },
  { kanji: "上", meaning: "above, up", onyomi: "ジョウ, ショウ", kunyomi: "うえ, あ-がる, かみ" },
  { kanji: "下", meaning: "below, down", onyomi: "カ, ゲ", kunyomi: "した, さ-がる, もと" },
  { kanji: "中", meaning: "middle, inside", onyomi: "チュウ", kunyomi: "なか" },
  { kanji: "左", meaning: "left", onyomi: "サ, シャ", kunyomi: "ひだり" },
  { kanji: "右", meaning: "right", onyomi: "ウ, ユウ", kunyomi: "みぎ" },
  { kanji: "年", meaning: "year", onyomi: "ネン", kunyomi: "とし" },
  { kanji: "先", meaning: "before, ahead", onyomi: "セン", kunyomi: "さき" },
  { kanji: "生", meaning: "life, birth", onyomi: "セイ, ショウ", kunyomi: "い-きる, う-まれる, なま" },
  { kanji: "私", meaning: "I, private", onyomi: "シ", kunyomi: "わたし, わたくし" },
  { kanji: "友", meaning: "friend", onyomi: "ユウ", kunyomi: "とも" },
  { kanji: "学", meaning: "study, learning", onyomi: "ガク", kunyomi: "まな-ぶ" },
  { kanji: "校", meaning: "school", onyomi: "コウ", kunyomi: "" },
  { kanji: "語", meaning: "language, word", onyomi: "ゴ", kunyomi: "かた-る" },
  { kanji: "文", meaning: "sentence, literature", onyomi: "ブン, モン", kunyomi: "ふみ" },
  { kanji: "字", meaning: "character, letter", onyomi: "ジ", kunyomi: "あざ" },
  { kanji: "本", meaning: "book, origin", onyomi: "ホン", kunyomi: "もと" },
  { kanji: "先週", meaning: "last week", onyomi: "センシュウ", kunyomi: "" },
  { kanji: "今", meaning: "now", onyomi: "コン, キン", kunyomi: "いま" },
  { kanji: "時", meaning: "time, hour", onyomi: "ジ", kunyomi: "とき" },
  { kanji: "分", meaning: "minute, part", onyomi: "ブン, フン, ブ", kunyomi: "わ-ける" },
  { kanji: "半", meaning: "half", onyomi: "ハン", kunyomi: "なか-ば" },
  { kanji: "午", meaning: "noon", onyomi: "ゴ", kunyomi: "" },
  { kanji: "前", meaning: "before, front", onyomi: "ゼン", kunyomi: "まえ" },
  { kanji: "後", meaning: "after, behind", onyomi: "ゴ, コウ", kunyomi: "あと, うし-ろ" },
  { kanji: "毎", meaning: "every", onyomi: "マイ", kunyomi: "" },
  { kanji: "週", meaning: "week", onyomi: "シュウ", kunyomi: "" },
  { kanji: "月曜日", meaning: "Monday", onyomi: "", kunyomi: "" },
  { kanji: "火曜日", meaning: "Tuesday", onyomi: "", kunyomi: "" },
  { kanji: "水曜日", meaning: "Wednesday", onyomi: "", kunyomi: "" },
  { kanji: "木曜日", meaning: "Thursday", onyomi: "", kunyomi: "" },
  { kanji: "金曜日", meaning: "Friday", onyomi: "", kunyomi: "" },
  { kanji: "土曜日", meaning: "Saturday", onyomi: "", kunyomi: "" },
  { kanji: "日曜日", meaning: "Sunday", onyomi: "", kunyomi: "" },
  { kanji: "男", meaning: "man, male", onyomi: "ダン, ナン", kunyomi: "おとこ" },
  { kanji: "女", meaning: "woman, female", onyomi: "ジョ, ニョ, ニョウ", kunyomi: "おんな" },
  { kanji: "子", meaning: "child", onyomi: "シ, ス", kunyomi: "こ" },
  { kanji: "犬", meaning: "dog", onyomi: "ケン", kunyomi: "いぬ" },
  { kanji: "天", meaning: "heaven, sky", onyomi: "テン", kunyomi: "" },
  { kanji: "気", meaning: "spirit, air", onyomi: "キ, ケ", kunyomi: "" },
  { kanji: "雨", meaning: "rain", onyomi: "ウ", kunyomi: "あめ, あま-" },
  { kanji: "電", meaning: "electricity", onyomi: "デン", kunyomi: "" },
  { kanji: "車", meaning: "car, vehicle", onyomi: "シャ", kunyomi: "くるま" },
  { kanji: "駅", meaning: "station", onyomi: "エキ", kunyomi: "" },
  { kanji: "道", meaning: "road, way", onyomi: "ドウ, トウ", kunyomi: "みち" },
  { kanji: "自", meaning: "self", onyomi: "ジ, シ", kunyomi: "みずか-ら" },
  { kanji: "何", meaning: "what", onyomi: "カ", kunyomi: "なに, なん" },
  { kanji: "右", meaning: "right", onyomi: "ウ, ユウ", kunyomi: "みぎ" },
  { kanji: "左", meaning: "left", onyomi: "サ, シャ", kunyomi: "ひだり" },
  { kanji: "外", meaning: "outside", onyomi: "ガイ, ゲ", kunyomi: "そと, ほか" },
  { kanji: "小", meaning: "small", onyomi: "ショウ", kunyomi: "ちい-さい, こ-, お-" },
  { kanji: "中", meaning: "middle", onyomi: "チュウ", kunyomi: "なか" },
  { kanji: "大", meaning: "big", onyomi: "ダイ, タイ", kunyomi: "おお-きい" },
  { kanji: "安", meaning: "cheap, safe", onyomi: "アン", kunyomi: "やす-い" },
  { kanji: "新", meaning: "new", onyomi: "シン", kunyomi: "あたら-しい" },
  { kanji: "古", meaning: "old", onyomi: "コ", kunyomi: "ふる-い" },
  { kanji: "長", meaning: "long, leader", onyomi: "チョウ", kunyomi: "なが-い" },
  { kanji: "多", meaning: "many", onyomi: "タ", kunyomi: "おお-い" },
  { kanji: "少", meaning: "few, little", onyomi: "ショウ", kunyomi: "すく-ない, すこ-し" },
  { kanji: "食", meaning: "eat", onyomi: "ショク, ジキ", kunyomi: "た-べる, く-う" },
  { kanji: "飲", meaning: "drink", onyomi: "イン", kunyomi: "の-む" },
  { kanji: "見", meaning: "see", onyomi: "ケン", kunyomi: "み-る" },
  { kanji: "聞", meaning: "hear, ask", onyomi: "ブン, モン", kunyomi: "き-く" },
  { kanji: "話", meaning: "speak, talk", onyomi: "ワ", kunyomi: "はな-す, はなし" },
  { kanji: "読", meaning: "read", onyomi: "ドク, トク, トウ", kunyomi: "よ-む" },
  { kanji: "書", meaning: "write", onyomi: "ショ", kunyomi: "か-く" },
  { kanji: "立", meaning: "stand", onyomi: "リツ, リュウ", kunyomi: "た-つ" },
  { kanji: "休", meaning: "rest", onyomi: "キュウ", kunyomi: "やす-む" },
  { kanji: "行", meaning: "go", onyomi: "コウ, ギョウ", kunyomi: "い-く, ゆ-く" },
  { kanji: "来", meaning: "come", onyomi: "ライ, タイ", kunyomi: "く-る, き-ます" },
  { kanji: "帰", meaning: "return", onyomi: "キ", kunyomi: "かえ-る" },
  { kanji: "買", meaning: "buy", onyomi: "バイ", kunyomi: "か-う" },
  { kanji: "売", meaning: "sell", onyomi: "バイ", kunyomi: "う-る" },
  { kanji: "会", meaning: "meet", onyomi: "カイ, エ", kunyomi: "あ-う" },
  { kanji: "社", meaning: "company, shrine", onyomi: "シャ", kunyomi: "" },
  { kanji: "話", meaning: "talk", onyomi: "ワ", kunyomi: "はな-す" },
  { kanji: "道", meaning: "road, way", onyomi: "ドウ", kunyomi: "みち" },
  { kanji: "駅", meaning: "station", onyomi: "エキ", kunyomi: "" },
  { kanji: "電", meaning: "electricity", onyomi: "デン", kunyomi: "" },
  { kanji: "車", meaning: "car", onyomi: "シャ", kunyomi: "くるま" },
  { kanji: "自", meaning: "self", onyomi: "ジ", kunyomi: "みずか-ら" },
  { kanji: "行", meaning: "go", onyomi: "コウ, ギョウ", kunyomi: "い-く" }
];
