const kanjiList = [
  { kanji: "一", meaning: "one", onyomi: "いち, いつ", kunyomi: "ひと-つ" },
  { kanji: "二", meaning: "two", onyomi: "に, じ", kunyomi: "ふた-つ" },
  { kanji: "三", meaning: "three", onyomi: "さん", kunyomi: "みっ-つ" },
  { kanji: "四", meaning: "four", onyomi: "し", kunyomi: "よん, よっ-つ, よ" },
  { kanji: "五", meaning: "five", onyomi: "ご", kunyomi: "いつ-つ" },
  { kanji: "六", meaning: "six", onyomi: "ろく, りく", kunyomi: "むっ-つ, むい" },
  { kanji: "七", meaning: "seven", onyomi: "しち", kunyomi: "なな-つ, なの" },
  { kanji: "八", meaning: "eight", onyomi: "はち", kunyomi: "やっ-つ, よう" },
  { kanji: "九", meaning: "nine", onyomi: "きゅう, く", kunyomi: "ここの-つ" },
  { kanji: "十", meaning: "ten", onyomi: "じゅう, じっ", kunyomi: "とお, と" },
  { kanji: "百", meaning: "hundred", onyomi: "ひゃく", kunyomi: "-" },
  { kanji: "千", meaning: "thousand", onyomi: "せん", kunyomi: "-" },
  { kanji: "円", meaning: "yen, circle", onyomi: "えん", kunyomi: "まる.い" },
  { kanji: "日", meaning: "day, sun", onyomi: "にち, じつ", kunyomi: "ひ, -び, -か" },
  { kanji: "月", meaning: "month, moon", onyomi: "げつ, がつ", kunyomi: "つき" },
  { kanji: "火", meaning: "fire", onyomi: "か", kunyomi: "ひ, -び, ほ-" },
  { kanji: "水", meaning: "water", onyomi: "すい", kunyomi: "みず" },
  { kanji: "木", meaning: "tree, wood", onyomi: "ぼく, もく", kunyomi: "き, こ-" },
  { kanji: "金", meaning: "gold, money", onyomi: "きん, こん", kunyomi: "かね, かな-" },
  { kanji: "土", meaning: "earth, soil", onyomi: "ど, と", kunyomi: "つち" },
  { kanji: "曜", meaning: "weekday", onyomi: "よう", kunyomi: "-" },
  { kanji: "上", meaning: "above, up", onyomi: "じょう, しょう", kunyomi: "うえ, あ-がる, かみ" },
  { kanji: "下", meaning: "below, down", onyomi: "か, げ", kunyomi: "した, さ-がる, もと" },
  { kanji: "中", meaning: "middle, inside", onyomi: "ちゅう", kunyomi: "なか" },
  { kanji: "左", meaning: "left", onyomi: "さ, しゃ", kunyomi: "ひだり" },
  { kanji: "右", meaning: "right", onyomi: "う, ゆう", kunyomi: "みぎ" },
  { kanji: "年", meaning: "year", onyomi: "ねん", kunyomi: "とし" },
  { kanji: "先", meaning: "before, ahead", onyomi: "せん", kunyomi: "さき" },
  { kanji: "生", meaning: "life, birth", onyomi: "せい, しょう", kunyomi: "い-きる, う-まれる, なま" },
  { kanji: "私", meaning: "I, private", onyomi: "し", kunyomi: "わたし, わたくし" },
  { kanji: "友", meaning: "friend", onyomi: "ゆう", kunyomi: "とも" },
  { kanji: "学", meaning: "study, learning", onyomi: "がく", kunyomi: "まな-ぶ" },
  { kanji: "校", meaning: "school", onyomi: "こう", kunyomi: "-" },
  { kanji: "語", meaning: "language, word", onyomi: "ご", kunyomi: "かた-る" },
  { kanji: "文", meaning: "sentence, literature", onyomi: "ぶん, もん", kunyomi: "ふみ" },
  { kanji: "字", meaning: "character, letter", onyomi: "じ", kunyomi: "あざ" },
  { kanji: "本", meaning: "book, origin", onyomi: "ほん", kunyomi: "もと" },
  { kanji: "先週", meaning: "last week", onyomi: "せんしゅう", kunyomi: "-" },
  { kanji: "今", meaning: "now", onyomi: "こん, きん", kunyomi: "いま" },
  { kanji: "時", meaning: "time, hour", onyomi: "じ", kunyomi: "とき" },
  { kanji: "分", meaning: "minute, part", onyomi: "ぶん, ふん, ぶ", kunyomi: "わ-ける" },
  { kanji: "半", meaning: "half", onyomi: "はん", kunyomi: "なか-ば" },
  { kanji: "午", meaning: "noon", onyomi: "ご", kunyomi: "-" },
  { kanji: "前", meaning: "before, front", onyomi: "ぜん", kunyomi: "まえ" },
  { kanji: "後", meaning: "after, behind", onyomi: "ご, こう", kunyomi: "あと, うし-ろ" },
  { kanji: "毎", meaning: "every", onyomi: "まい", kunyomi: "-" },
  { kanji: "週", meaning: "week", onyomi: "しゅう", kunyomi: "-" },
  { kanji: "月曜日", meaning: "Monday", onyomi: "げつ, がつ", kunyomi: "つき" },
  { kanji: "火曜日", meaning: "Tuesday", onyomi: "か", kunyomi: "ひ, ほ" },
  { kanji: "水曜日", meaning: "Wednesday", onyomi: "すい", kunyomi: "みず" },
  { kanji: "木曜日", meaning: "Thursday", onyomi: "もく, ぼく", kunyomi: "き, こ" },
  { kanji: "金曜日", meaning: "Friday", onyomi: "きん, こん", kunyomi: "かね, かな" },
  { kanji: "土曜日", meaning: "Saturday", onyomi: "ど, と", kunyomi: "つち" },
  { kanji: "日曜日", meaning: "Sunday", onyomi: "にち, じつ", kunyomi: "ひ, -び, -か" },
  { kanji: "男", meaning: "man, male", onyomi: "だん, なん", kunyomi: "おとこ" },
  { kanji: "女", meaning: "woman, female", onyomi: "じょ, にょ, にょう", kunyomi: "おんな" },
  { kanji: "子", meaning: "child", onyomi: "し, す", kunyomi: "こ" },
  { kanji: "犬", meaning: "dog", onyomi: "けん", kunyomi: "いぬ" },
  { kanji: "天", meaning: "heaven, sky", onyomi: "てん", kunyomi: "-" },
  { kanji: "気", meaning: "spirit, air", onyomi: "き, け", kunyomi: "-" },
  { kanji: "雨", meaning: "rain", onyomi: "う", kunyomi: "あめ, あま-" },
  { kanji: "電", meaning: "electricity", onyomi: "でん", kunyomi: "-" },
  { kanji: "車", meaning: "car, vehicle", onyomi: "しゃ", kunyomi: "くるま" },
  { kanji: "駅", meaning: "station", onyomi: "えき", kunyomi: "-" },
  { kanji: "道", meaning: "road, way", onyomi: "どう, とう", kunyomi: "みち" },
  { kanji: "自", meaning: "self", onyomi: "じ, し", kunyomi: "みずか-ら" },
  { kanji: "何", meaning: "what", onyomi: "か", kunyomi: "なに, なん" },
  { kanji: "右", meaning: "right", onyomi: "う, ゆう", kunyomi: "みぎ" },
  { kanji: "左", meaning: "left", onyomi: "さ, しゃ", kunyomi: "ひだり" },
  { kanji: "外", meaning: "outside", onyomi: "がい, げ", kunyomi: "そと, ほか" },
  { kanji: "小", meaning: "small", onyomi: "しょう", kunyomi: "ちい-さい, こ-, お-" },
  { kanji: "中", meaning: "middle", onyomi: "ちゅう", kunyomi: "なか" },
  { kanji: "大", meaning: "big", onyomi: "だい, たい", kunyomi: "おお-きい" },
  { kanji: "安", meaning: "cheap, safe", onyomi: "あん", kunyomi: "やす-い" },
  { kanji: "新", meaning: "new", onyomi: "しん", kunyomi: "あたら-しい" },
  { kanji: "古", meaning: "old", onyomi: "こ", kunyomi: "ふる-い" },
  { kanji: "長", meaning: "long, leader", onyomi: "ちょう", kunyomi: "なが-い" },
  { kanji: "多", meaning: "many", onyomi: "た", kunyomi: "おお-い" },
  { kanji: "少", meaning: "few, little", onyomi: "しょう", kunyomi: "すく-ない, すこ-し" },
  { kanji: "食", meaning: "eat", onyomi: "しょく, じき", kunyomi: "た-べる, く-う" },
  { kanji: "飲", meaning: "drink", onyomi: "いん", kunyomi: "の-む" },
  { kanji: "見", meaning: "see", onyomi: "けん", kunyomi: "み-る" },
  { kanji: "聞", meaning: "hear, ask", onyomi: "ぶん, もん", kunyomi: "き-く" },
  { kanji: "話", meaning: "speak, talk", onyomi: "わ", kunyomi: "はな-す, はなし" },
  { kanji: "読", meaning: "read", onyomi: "どく, とく, とう", kunyomi: "よ-む" },
  { kanji: "書", meaning: "write", onyomi: "しょ", kunyomi: "か-く" },
  { kanji: "立", meaning: "stand", onyomi: "りつ, りゅう", kunyomi: "た-つ" },
  { kanji: "休", meaning: "rest", onyomi: "きゅう", kunyomi: "やす-む" },
  { kanji: "行", meaning: "go", onyomi: "こう, ぎょう", kunyomi: "い-く, ゆ-く" },
  { kanji: "来", meaning: "come", onyomi: "らい, たい", kunyomi: "く-る, き-ます" },
  { kanji: "帰", meaning: "return", onyomi: "き", kunyomi: "かえ-る" },
  { kanji: "買", meaning: "buy", onyomi: "ばい", kunyomi: "か-う" },
  { kanji: "売", meaning: "sell", onyomi: "ばい", kunyomi: "う-る" },
  { kanji: "会", meaning: "meet", onyomi: "かい, え", kunyomi: "あ-う" },
  { kanji: "社", meaning: "company, shrine", onyomi: "しゃ", kunyomi: "-" },
  { kanji: "話", meaning: "talk", onyomi: "わ", kunyomi: "はな-す" },
  { kanji: "道", meaning: "road, way", onyomi: "どう", kunyomi: "みち" },
  { kanji: "駅", meaning: "station", onyomi: "えき", kunyomi: "-" },
  { kanji: "電", meaning: "electricity", onyomi: "でん", kunyomi: "-" },
  { kanji: "車", meaning: "car", onyomi: "しゃ", kunyomi: "くるま" },
  { kanji: "自", meaning: "self", onyomi: "じ", kunyomi: "みずか-ら" },
  { kanji: "行", meaning: "go", onyomi: "こう, ぎょう", kunyomi: "い-く" }
];