const kanjiN4List = [
  { kanji: "会", meaning: "meeting, meet", onyomi: "かい", kunyomi: "あ-う" },
  { kanji: "同", meaning: "same, agree, equal", onyomi: "どう", kunyomi: "おな-じ" },
  { kanji: "事", meaning: "matter, thing, fact", onyomi: "じ", kunyomi: "こと" },
  { kanji: "自", meaning: "oneself", onyomi: "じ, し", kunyomi: "みずか-ら" },
  { kanji: "社", meaning: "company, shrine", onyomi: "しゃ", kunyomi: "やしろ" },
  { kanji: "発", meaning: "departure, emit, start", onyomi: "はつ, ほつ", kunyomi: "-" },
  { kanji: "者", meaning: "person, someone", onyomi: "しゃ", kunyomi: "もの" },
  { kanji: "地", meaning: "ground, earth", onyomi: "ち, じ", kunyomi: "-" },
  { kanji: "業", meaning: "business, vocation, performance", onyomi: "ぎょう", kunyomi: "わざ" },
  { kanji: "方", meaning: "direction, person, method", onyomi: "ほう", kunyomi: "かた" },
  { kanji: "新", meaning: "new", onyomi: "しん", kunyomi: "あたら-しい, あら-た" },
  { kanji: "場", meaning: "place, location", onyomi: "じょう", kunyomi: "ば" },
  { kanji: "員", meaning: "member, employee", onyomi: "いん", kunyomi: "-" },
  { kanji: "立", meaning: "stand, rise", onyomi: "りつ", kunyomi: "た-つ" },
  { kanji: "開", meaning: "open, unfold", onyomi: "かい", kunyomi: "ひら-く, あ-ける" },
  { kanji: "手", meaning: "hand", onyomi: "しゅ", kunyomi: "て" },
  { kanji: "力", meaning: "power, strength", onyomi: "りょく, りき", kunyomi: "ちから" },
  { kanji: "問", meaning: "question, ask, problem", onyomi: "もん", kunyomi: "と-う" },
  { kanji: "代", meaning: "substitute, change, period", onyomi: "だい", kunyomi: "か-わり" },
  { kanji: "明", meaning: "bright, light", onyomi: "めい, みょう", kunyomi: "あか-るい" },
  { kanji: "動", meaning: "move, motion, change", onyomi: "どう", kunyomi: "うご-く" },
  { kanji: "京", meaning: "capital", onyomi: "きょう, けい, きん", kunyomi: "みやこ" },
  { kanji: "目", meaning: "eye, class, look", onyomi: "もく, ぼく", kunyomi: "め" },
  { kanji: "通", meaning: "traffic, pass through, commute", onyomi: "つう", kunyomi: "とお-る, かよ-う" },
  { kanji: "言", meaning: "say, word", onyomi: "げん, ごん", kunyomi: "い-う, こと" },
  { kanji: "理", meaning: "logic, reason, truth", onyomi: "り", kunyomi: "-" },
  { kanji: "体", meaning: "body, substance", onyomi: "たい", kunyomi: "からだ" },
  { kanji: "田", meaning: "rice field", onyomi: "でん", kunyomi: "た" },
  { kanji: "主", meaning: "main, master, lord", onyomi: "しゅ", kunyomi: "ぬし, おも" },
  { kanji: "題", meaning: "topic, subject", onyomi: "だい", kunyomi: "-" },
  { kanji: "意", meaning: "idea, mind, meaning", onyomi: "い", kunyomi: "-" },
  { kanji: "不", meaning: "negative, non-, bad", onyomi: "ふ, ぶ", kunyomi: "-" },
  { kanji: "作", meaning: "make, produce, prepare", onyomi: "さく, さ", kunyomi: "つく-る" },
  { kanji: "用", meaning: "use, business, employ", onyomi: "よう", kunyomi: "もち-いる" },
  { kanji: "度", meaning: "degree, occurrence, time", onyomi: "ど, たく", kunyomi: "たび" },
  { kanji: "強", meaning: "strong", onyomi: "きょう, ごう", kunyomi: "つよ-い" },
  { kanji: "公", meaning: "public, official", onyomi: "こう", kunyomi: "-" },
  { kanji: "持", meaning: "hold, have", onyomi: "じ", kunyomi: "も-つ" },
  { kanji: "野", meaning: "field, plains", onyomi: "や", kunyomi: "の" },
  { kanji: "以", meaning: "by means of, compared with", onyomi: "い", kunyomi: "もっ-て" },
  { kanji: "思", meaning: "think", onyomi: "し", kunyomi: "おも-う" },
  { kanji: "家", meaning: "house, home, family", onyomi: "か", kunyomi: "いえ, や, うち" },
  { kanji: "世", meaning: "world, generation, society", onyomi: "せい, せ", kunyomi: "よ" },
  { kanji: "多", meaning: "many, much", onyomi: "た", kunyomi: "おお-い" },
  { kanji: "正", meaning: "correct, justice, righteous", onyomi: "せい, しょう", kunyomi: "ただ-しい, まさ-に" },
  { kanji: "安", meaning: "safe, peaceful, cheap", onyomi: "あん", kunyomi: "やす-い" },
  { kanji: "院", meaning: "institution, temple, school", onyomi: "いん", kunyomi: "-" },
  { kanji: "心", meaning: "heart, mind, spirit", onyomi: "しん", kunyomi: "こころ" },
  { kanji: "界", meaning: "world, boundary", onyomi: "かい", kunyomi: "-" },
  { kanji: "教", meaning: "teach, faith, doctrine", onyomi: "きょう", kunyomi: "おし-える, おそ-わる" },
  { kanji: "文", meaning: "sentence, literature, style", onyomi: "ぶん, もん", kunyomi: "ふみ" },
  { kanji: "元", meaning: "origin, beginning, former", onyomi: "げん, がん", kunyomi: "もと" },
  { kanji: "重", meaning: "heavy, important", onyomi: "じゅう, ちょう", kunyomi: "おも-い, かさ-ねる" },
  { kanji: "近", meaning: "near, close", onyomi: "きん", kunyomi: "ちか-い" },
  { kanji: "考", meaning: "consider, think over", onyomi: "こう", kunyomi: "かんが-える" },
  { kanji: "画", meaning: "picture, brush stroke", onyomi: "が, かく", kunyomi: "えが-く" },
  { kanji: "海", meaning: "sea, ocean", onyomi: "かい", kunyomi: "うみ" },
  { kanji: "売", meaning: "sell", onyomi: "ばい", kunyomi: "う-る" },
  { kanji: "知", meaning: "know, wisdom", onyomi: "ち", kunyomi: "し-る" },
  { kanji: "道", meaning: "road, way, course", onyomi: "どう", kunyomi: "みち" },
  { kanji: "集", meaning: "gather, meet", onyomi: "しゅう", kunyomi: "あつ-める" },
  { kanji: "別", meaning: "separate, divide", onyomi: "べつ", kunyomi: "わか-れる, わ-ける" },
  { kanji: "物", meaning: "thing, object, matter", onyomi: "ぶつ, もつ", kunyomi: "もの" },
  { kanji: "使", meaning: "use, messenger", onyomi: "し", kunyomi: "つか-う" },
  { kanji: "品", meaning: "goods, article, refinement", onyomi: "ひん", kunyomi: "しな" },
  { kanji: "計", meaning: "plan, measure", onyomi: "けい", kunyomi: "はか-る" },
  { kanji: "死", meaning: "death, die", onyomi: "し", kunyomi: "し-ぬ" },
  { kanji: "特", meaning: "special", onyomi: "とく", kunyomi: "-" },
  { kanji: "私", meaning: "private, I, me", onyomi: "し", kunyomi: "わたし, わたくし" },
  { kanji: "始", meaning: "begin, commence", onyomi: "し", kunyomi: "はじ-める" },
  { kanji: "朝", meaning: "morning", onyomi: "ちょう", kunyomi: "あさ" },
  { kanji: "運", meaning: "carry, luck, transport", onyomi: "うん", kunyomi: "はこ-ぶ" },
  { kanji: "終", meaning: "end, finish", onyomi: "しゅう", kunyomi: "お-わる" },
  { kanji: "台", meaning: "stand, pedestal, counter for machines", onyomi: "だい, たい", kunyomi: "うてな" },
  { kanji: "広", meaning: "wide, broad, spacious", onyomi: "こう", kunyomi: "ひろ-い" },
  { kanji: "住", meaning: "dwell, live, reside", onyomi: "じゅう, ちゅう", kunyomi: "す-む" },
  { kanji: "無", meaning: "nothing, none, not", onyomi: "む, ぶ", kunyomi: "な-い" },
  { kanji: "真", meaning: "true, reality", onyomi: "しん", kunyomi: "ま, まこと" },
  { kanji: "有", meaning: "have, exist", onyomi: "ゆう, う", kunyomi: "あ-る" },
  { kanji: "口", meaning: "mouth", onyomi: "こう", kunyomi: "くち" },
  { kanji: "少", meaning: "few, little", onyomi: "しょう", kunyomi: "すく-ない, すこ-し" },
  { kanji: "町", meaning: "town, block, street", onyomi: "ちょう", kunyomi: "まち" },
  { kanji: "料", meaning: "fee, materials", onyomi: "りょう", kunyomi: "-" },
  { kanji: "工", meaning: "craft, construction", onyomi: "こう, く, ぐ", kunyomi: "-" },
  { kanji: "建", meaning: "build", onyomi: "けん, こん", kunyomi: "た-てる" },
  { kanji: "空", meaning: "empty, sky, void", onyomi: "くう", kunyomi: "そら, から, あ-く, す-く" },
  { kanji: "急", meaning: "hurry, emergency, sudden", onyomi: "きゅう", kunyomi: "いそ-ぐ" },
  { kanji: "止", meaning: "stop, halt", onyomi: "し", kunyomi: "と-まる, や-める" },
  { kanji: "送", meaning: "send, escort", onyomi: "そう", kunyomi: "おく-る" },
  { kanji: "切", meaning: "cut, be sharp", onyomi: "せつ, さい", kunyomi: "き-る" },
  { kanji: "転", meaning: "turn, roll, change", onyomi: "てん", kunyomi: "ころ-がる" },
  { kanji: "研", meaning: "polish, study, sharpen", onyomi: "けん", kunyomi: "と-ぐ" },
  { kanji: "足", meaning: "leg, foot, sufficient", onyomi: "そく", kunyomi: "あし, た-りる" },
  { kanji: "究", meaning: "research, study", onyomi: "きゅう", kunyomi: "-" },
  { kanji: "楽", meaning: "music, comfort, ease", onyomi: "がく, らく", kunyomi: "たの-しい" },
  { kanji: "起", meaning: "wake up, get up, rouse", onyomi: "き", kunyomi: "お-きる, お-こす" },
  { kanji: "着", meaning: "arrive, wear", onyomi: "ちゃく", kunyomi: "き-る, つ-く" },
  { kanji: "店", meaning: "store, shop", onyomi: "てん", kunyomi: "みせ" },
  { kanji: "病", meaning: "ill, sick", onyomi: "びょう", kunyomi: "や-む" },
  { kanji: "質", meaning: "quality, substance, matter", onyomi: "しつ, しち", kunyomi: "たち, ただ-す" },
  { kanji: "待", meaning: "wait, depend on", onyomi: "たい", kunyomi: "ま-つ" },
  { kanji: "試", meaning: "test, try, attempt", onyomi: "し", kunyomi: "こころ-みる, ため-す" },
  { kanji: "族", meaning: "family, tribe", onyomi: "ぞく", kunyomi: "-" },
  { kanji: "銀", meaning: "silver", onyomi: "ぎん", kunyomi: "-" },
  { kanji: "早", meaning: "early, fast", onyomi: "そう, さ", kunyomi: "はや-い" },
  { kanji: "映", meaning: "reflect, projection", onyomi: "えい", kunyomi: "うつ-る, は-える" },
  { kanji: "親", meaning: "parent, relative, intimacy", onyomi: "しん", kunyomi: "おや, した-しい" },
  { kanji: "験", meaning: "test, verification, effect", onyomi: "けん", kunyomi: "-" },
  { kanji: "英", meaning: "English, outstanding", onyomi: "えい", kunyomi: "-" },
  { kanji: "医", meaning: "doctor, medicine", onyomi: "い", kunyomi: "-" },
  { kanji: "仕", meaning: "serve, attend, doing", onyomi: "し", kunyomi: "-" },
  { kanji: "去", meaning: "past, leave, quit", onyomi: "きょ, こ", kunyomi: "さ-る" },
  { kanji: "味", meaning: "flavor, taste", onyomi: "み", kunyomi: "あじ" },
  { kanji: "写", meaning: "copy, photograph, describe", onyomi: "しゃ", kunyomi: "うつ-す, うつ-る" },
  { kanji: "字", meaning: "character, letter, word", onyomi: "じ", kunyomi: "-" },
  { kanji: "答", meaning: "answer, solution", onyomi: "とう", kunyomi: "こた-える" },
  { kanji: "夜", meaning: "night, evening", onyomi: "や", kunyomi: "よ, よる" },
  { kanji: "音", meaning: "sound, noise", onyomi: "おん", kunyomi: "おと, ね" },
  { kanji: "注", meaning: "pour, concentrate on", onyomi: "ちゅう", kunyomi: "そそ-ぐ, さ-す" },
  { kanji: "帰", meaning: "return, homecoming", onyomi: "き", kunyomi: "かえ-る, かえ-す" },
  { kanji: "古", meaning: "old", onyomi: "こ", kunyomi: "ふる-い" },
  { kanji: "歌", meaning: "song, sing", onyomi: "か", kunyomi: "うた, うた-う" },
  { kanji: "買", meaning: "buy", onyomi: "ばい", kunyomi: "か-う" },
  { kanji: "悪", meaning: "bad, evil, wrong", onyomi: "あく", kunyomi: "わる-い" },
  { kanji: "図", meaning: "map, drawing, plan", onyomi: "ず, と", kunyomi: "はか-る" },
  { kanji: "週", meaning: "week", onyomi: "しゅう", kunyomi: "-" },
  { kanji: "室", meaning: "room, chamber", onyomi: "しつ", kunyomi: "むろ" },
  { kanji: "歩", meaning: "walk, step", onyomi: "ほ, ぶ", kunyomi: "ある-く, あゆ-む" },
  { kanji: "風", meaning: "wind, style, manner", onyomi: "ふう, ふ", kunyomi: "かぜ, かざ-" },
  { kanji: "紙", meaning: "paper", onyomi: "し", kunyomi: "かみ" },
  { kanji: "黒", meaning: "black", onyomi: "こく", kunyomi: "くろ" },
  { kanji: "花", meaning: "flower", onyomi: "か, け", kunyomi: "はな" },
  { kanji: "春", meaning: "spring", onyomi: "しゅん", kunyomi: "はる" },
  { kanji: "赤", meaning: "red", onyomi: "せき, しゃく", kunyomi: "あか-い" },
  { kanji: "青", meaning: "blue", onyomi: "せい, しょう", kunyomi: "あお-い" },
  { kanji: "館", meaning: "building, mansion", onyomi: "かん", kunyomi: "やかた" },
  { kanji: "屋", meaning: "roof, house, shop", onyomi: "おく", kunyomi: "や" },
  { kanji: "色", meaning: "color", onyomi: "しょく, しき", kunyomi: "いろ" },
  { kanji: "走", meaning: "run", onyomi: "そう", kunyomi: "はし-る" },
  { kanji: "秋", meaning: "autumn, fall", onyomi: "しゅう", kunyomi: "あき" },
  { kanji: "夏", meaning: "summer", onyomi: "か, げ", kunyomi: "なつ" },
  { kanji: "習", meaning: "learn", onyomi: "しゅう", kunyomi: "なら-う" },
  { kanji: "駅", meaning: "station", onyomi: "えき", kunyomi: "-" },
  { kanji: "洋", meaning: "ocean, Western style", onyomi: "よう", kunyomi: "-" },
  { kanji: "旅", meaning: "trip, travel", onyomi: "りょ", kunyomi: "たび" },
  { kanji: "服", meaning: "clothing, obey", onyomi: "ふく", kunyomi: "-" },
  { kanji: "夕", meaning: "evening", onyomi: "-", kunyomi: "ゆう" },
  { kanji: "借", meaning: "borrow, rent", onyomi: "しゃく", kunyomi: "か-りる" },
  { kanji: "曜", meaning: "weekday", onyomi: "よう", kunyomi: "-" },
  { kanji: "飲", meaning: "drink", onyomi: "いん", kunyomi: "の-む" },
  { kanji: "肉", meaning: "meat", onyomi: "にく", kunyomi: "-" },
  { kanji: "貸", meaning: "lend", onyomi: "たい", kunyomi: "か-す, かし" },
  { kanji: "堂", meaning: "hall, public chamber", onyomi: "どう", kunyomi: "-" },
  { kanji: "鳥", meaning: "bird, chicken", onyomi: "ちょう", kunyomi: "とり" },
  { kanji: "飯", meaning: "meal, rice", onyomi: "はん", kunyomi: "めし" },
  { kanji: "勉", meaning: "effort, endeavor", onyomi: "べん", kunyomi: "つと-める" },
  { kanji: "冬", meaning: "winter", onyomi: "とう", kunyomi: "ふゆ" },
  { kanji: "昼", meaning: "daytime, noon", onyomi: "ちゅう", kunyomi: "ひる" },
  { kanji: "茶", meaning: "tea", onyomi: "ちゃ, さ", kunyomi: "-" },
  { kanji: "弟", meaning: "younger brother", onyomi: "てい, だい, で", kunyomi: "おとうと" },
  { kanji: "牛", meaning: "cow", onyomi: "ぎゅう", kunyomi: "うし" },
  { kanji: "魚", meaning: "fish", onyomi: "ぎょ", kunyomi: "うお, さかな" },
  { kanji: "兄", meaning: "elder brother", onyomi: "きょう, けい", kunyomi: "あに" },
  { kanji: "犬", meaning: "dog", onyomi: "けん", kunyomi: "いぬ" },
  { kanji: "妹", meaning: "younger sister", onyomi: "まい", kunyomi: "いもうと" },
  { kanji: "姉", meaning: "elder sister", onyomi: "し", kunyomi: "あね" },
  { kanji: "漢", meaning: "China, Chinese", onyomi: "かん", kunyomi: "-" }
];
