const vocabN5List = [
  { word: "浴びる", reading: "あびる", meaning: "to bathe, to shower", type: "verb" },
  { word: "危ない", reading: "あぶない", meaning: "dangerous", type: "i-adjective" },
  { word: "あっち", reading: "あっち", meaning: "over there", type: "hiragana, pronoun" },
  { word: "あなた", reading: "あなた", meaning: "you", type: "hiragana, pronoun" },
  { word: "あの", reading: "あの", meaning: "that", type: "hiragana, pre-noun adjective" },
  { word: "アパート", reading: "アパート", meaning: "apartment", type: "katakana, noun" },
  { word: "洗う", reading: "あらう", meaning: "to wash", type: "verb" },
  { word: "あれ", reading: "あれ", meaning: "that over there", type: "hiragana, pronoun" },
  { word: "ある", reading: "ある", meaning: "to exist, to have", type: "hiragana, verb" },
  { word: "歩く", reading: "あるく", meaning: "to walk", type: "verb" },
  { word: "朝", reading: "あさ", meaning: "morning", type: "noun" },
  { word: "朝ご飯", reading: "あさごはん", meaning: "breakfast", type: "noun" },
  { word: "明後日", reading: "あさって", meaning: "day after tomorrow", type: "noun" },
  { word: "足", reading: "あし", meaning: "foot, leg", type: "noun" },
  { word: "明日", reading: "あした", meaning: "tomorrow", type: "noun" },
  { word: "遊ぶ", reading: "あそぶ", meaning: "to play", type: "verb" },
  { word: "あそこ", reading: "あそこ", meaning: "over there", type: "hiragana, pronoun" },
  { word: "頭", reading: "あたま", meaning: "head", type: "noun" },
  { word: "新しい", reading: "あたらしい", meaning: "new", type: "i-adjective" },
  { word: "暑い", reading: "あつい", meaning: "hot weather", type: "i-adjective" },
  { word: "会う", reading: "あう", meaning: "to meet", type: "verb" },
  { word: "晩ご飯", reading: "ばんごはん", meaning: "dinner", type: "noun" },
  { word: "番号", reading: "ばんごう", meaning: "number", type: "noun" },
  { word: "バス", reading: "バス", meaning: "bus", type: "katakana, noun" },
  { word: "ベッド", reading: "ベッド", meaning: "bed", type: "katakana, noun" },
  { word: "勉強", reading: "べんきょう", meaning: "study", type: "noun, suru verb" },
  { word: "便利", reading: "べんり", meaning: "convenient", type: "na-adjective" },
  { word: "ボールペン", reading: "ボールペン", meaning: "ballpoint pen", type: "katakana, noun" },
  { word: "ボタン", reading: "ボタン", meaning: "button", type: "katakana, noun" },
  { word: "帽子", reading: "ぼうし", meaning: "hat, cap", type: "noun" },
  { word: "病院", reading: "びょういん", meaning: "hospital", type: "noun" },
  { word: "病気", reading: "びょうき", meaning: "illness, sickness", type: "noun" },
  { word: "茶色", reading: "ちゃいろ", meaning: "brown", type: "noun" },
  { word: "父", reading: "ちち", meaning: "father", type: "noun" },
  { word: "違う", reading: "ちがう", meaning: "to differ, to be wrong", type: "verb" },
  { word: "小さい", reading: "ちいさい", meaning: "small", type: "i-adjective" },
  { word: "近い", reading: "ちかい", meaning: "near, close", type: "i-adjective" },
  { word: "地下鉄", reading: "ちかてつ", meaning: "subway", type: "noun" },
  { word: "地図", reading: "ちず", meaning: "map", type: "noun" },
  { word: "ちょっと", reading: "ちょっと", meaning: "a little", type: "hiragana, adverb" },
  { word: "台所", reading: "だいどころ", meaning: "kitchen", type: "noun" },
  { word: "大学", reading: "だいがく", meaning: "university", type: "noun" },
  { word: "大丈夫", reading: "だいじょうぶ", meaning: "OK, all right", type: "na-adjective" },
  { word: "誰", reading: "だれ", meaning: "who", type: "pronoun" },
  { word: "誰か", reading: "だれか", meaning: "someone", type: "pronoun" },
  { word: "出す", reading: "だす", meaning: "to take out, to send", type: "verb" },
  { word: "出口", reading: "でぐち", meaning: "exit", type: "noun" },
  { word: "出かける", reading: "でかける", meaning: "to go out", type: "verb" },
  { word: "電気", reading: "でんき", meaning: "electricity, light", type: "noun" },
  { word: "電車", reading: "でんしゃ", meaning: "train", type: "noun" },
  { word: "電話", reading: "でんわ", meaning: "telephone", type: "noun, suru verb" },
  { word: "デパート", reading: "デパート", meaning: "department store", type: "katakana, noun" },
  { word: "出る", reading: "でる", meaning: "to leave, to exit", type: "verb" },
  { word: "ドア", reading: "ドア", meaning: "door", type: "katakana, noun" },
  { word: "どこ", reading: "どこ", meaning: "where", type: "hiragana, pronoun" },
  { word: "どう", reading: "どう", meaning: "how", type: "hiragana, adverb" },
  { word: "動物", reading: "どうぶつ", meaning: "animal", type: "noun" },
  { word: "どうぞ", reading: "どうぞ", meaning: "please, go ahead", type: "hiragana, expression" },
  { word: "土曜日", reading: "どようび", meaning: "Saturday", type: "noun" },
  { word: "絵", reading: "え", meaning: "picture", type: "noun" },
  { word: "ええ", reading: "ええ", meaning: "yes", type: "hiragana, expression" },
  { word: "映画", reading: "えいが", meaning: "movie", type: "noun" },
  { word: "映画館", reading: "えいがかん", meaning: "movie theater", type: "noun" },
  { word: "英語", reading: "えいご", meaning: "English language", type: "noun" },
  { word: "駅", reading: "えき", meaning: "station", type: "noun" },
  { word: "鉛筆", reading: "えんぴつ", meaning: "pencil", type: "noun" },
  { word: "エレベーター", reading: "エレベーター", meaning: "elevator", type: "katakana, noun" },
  { word: "学校", reading: "がっこう", meaning: "school", type: "noun" },
  { word: "学生", reading: "がくせい", meaning: "student", type: "noun" },
  { word: "外国", reading: "がいこく", meaning: "foreign country", type: "noun" },
  { word: "元気", reading: "げんき", meaning: "healthy, energetic", type: "na-adjective" },
  { word: "銀行", reading: "ぎんこう", meaning: "bank", type: "noun" },
  { word: "ご飯", reading: "ごはん", meaning: "rice, meal", type: "noun" },
  { word: "入る", reading: "はいる", meaning: "to enter", type: "verb" },
  { word: "話す", reading: "はなす", meaning: "to speak", type: "verb" },
  { word: "母", reading: "はは", meaning: "mother", type: "noun" },
  { word: "早い", reading: "はやい", meaning: "early, fast", type: "i-adjective" },
  { word: "本", reading: "ほん", meaning: "book", type: "noun" },
  { word: "本屋", reading: "ほんや", meaning: "bookstore", type: "noun" },
  { word: "いくら", reading: "いくら", meaning: "how much", type: "hiragana, adverb" },
  { word: "今", reading: "いま", meaning: "now", type: "noun" },
  { word: "犬", reading: "いぬ", meaning: "dog", type: "noun" },
  { word: "妹", reading: "いもうと", meaning: "younger sister", type: "noun" },
  { word: "忙しい", reading: "いそがしい", meaning: "busy", type: "i-adjective" },
  { word: "医者", reading: "いしゃ", meaning: "doctor", type: "noun" },
  { word: "一緒", reading: "いっしょ", meaning: "together", type: "noun, adverb" },
  { word: "行く", reading: "いく", meaning: "to go", type: "verb" },
  { word: "色", reading: "いろ", meaning: "color", type: "noun" },
  { word: "いろいろ", reading: "いろいろ", meaning: "various", type: "hiragana, na-adjective" },
  { word: "入口", reading: "いりぐち", meaning: "entrance", type: "noun" },
  { word: "カメラ", reading: "カメラ", meaning: "camera", type: "katakana, noun" },
  { word: "紙", reading: "かみ", meaning: "paper", type: "noun" },
  { word: "漢字", reading: "かんじ", meaning: "kanji", type: "noun" },
  { word: "コーヒー", reading: "コーヒー", meaning: "coffee", type: "katakana, noun" },
  { word: "コピー", reading: "コピー", meaning: "copy", type: "katakana, noun, suru verb" },
  { word: "パン", reading: "パン", meaning: "bread", type: "katakana, noun" },
  { word: "ペン", reading: "ペン", meaning: "pen", type: "katakana, noun" },
  { word: "レストラン", reading: "レストラン", meaning: "restaurant", type: "katakana, noun" },
  { word: "テレビ", reading: "テレビ", meaning: "television", type: "katakana, noun" }
];
