const vocabN4List = [
  { word: "あいさつ", reading: "あいさつ", meaning: "greeting", type: "hiragana, noun" },
  { word: "間", reading: "あいだ", meaning: "between, interval", type: "noun" },
  { word: "合う", reading: "あう", meaning: "to fit, to suit", type: "verb" },
  { word: "赤ちゃん", reading: "あかちゃん", meaning: "baby", type: "noun" },
  { word: "アクセサリー", reading: "アクセサリー", meaning: "accessory", type: "katakana, noun" },
  { word: "あんな", reading: "あんな", meaning: "such", type: "hiragana, pre-noun adjective" },
  { word: "安心", reading: "あんしん", meaning: "relief, peace of mind", type: "noun, suru verb" },
  { word: "安全", reading: "あんぜん", meaning: "safety", type: "na-adjective" },
  { word: "以下", reading: "いか", meaning: "less than, below", type: "noun" },
  { word: "以外", reading: "いがい", meaning: "except, other than", type: "noun" },
  { word: "医学", reading: "いがく", meaning: "medical science", type: "noun" },
  { word: "意見", reading: "いけん", meaning: "opinion", type: "noun" },
  { word: "石", reading: "いし", meaning: "stone", type: "noun" },
  { word: "急ぐ", reading: "いそぐ", meaning: "to hurry", type: "verb" },
  { word: "一度", reading: "いちど", meaning: "once, one time", type: "noun, adverb" },
  { word: "一生懸命", reading: "いっしょうけんめい", meaning: "with all one's effort", type: "na-adjective, adverb" },
  { word: "いっぱい", reading: "いっぱい", meaning: "full, a lot", type: "hiragana, adverb" },
  { word: "以内", reading: "いない", meaning: "within, inside of", type: "noun" },
  { word: "田舎", reading: "いなか", meaning: "countryside", type: "noun" },
  { word: "祈る", reading: "いのる", meaning: "to pray", type: "verb" },
  { word: "受付", reading: "うけつけ", meaning: "reception desk", type: "noun" },
  { word: "動く", reading: "うごく", meaning: "to move", type: "verb" },
  { word: "うそ", reading: "うそ", meaning: "lie", type: "hiragana, noun" },
  { word: "美しい", reading: "うつくしい", meaning: "beautiful", type: "i-adjective" },
  { word: "写す", reading: "うつす", meaning: "to copy, to photograph", type: "verb" },
  { word: "打つ", reading: "うつ", meaning: "to hit, to type", type: "verb" },
  { word: "腕", reading: "うで", meaning: "arm", type: "noun" },
  { word: "運転", reading: "うんてん", meaning: "driving", type: "noun, suru verb" },
  { word: "運転手", reading: "うんてんしゅ", meaning: "driver", type: "noun" },
  { word: "運動", reading: "うんどう", meaning: "exercise", type: "noun, suru verb" },
  { word: "エスカレーター", reading: "エスカレーター", meaning: "escalator", type: "katakana, noun" },
  { word: "選ぶ", reading: "えらぶ", meaning: "to choose", type: "verb" },
  { word: "遠慮", reading: "えんりょ", meaning: "restraint, reserve", type: "noun, suru verb" },
  { word: "お祝い", reading: "おいわい", meaning: "celebration, congratulations", type: "noun" },
  { word: "お菓子", reading: "おかし", meaning: "sweets, snacks", type: "noun" },
  { word: "屋上", reading: "おくじょう", meaning: "rooftop", type: "noun" },
  { word: "奥さん", reading: "おくさん", meaning: "wife", type: "noun" },
  { word: "送る", reading: "おくる", meaning: "to send", type: "verb" },
  { word: "お宅", reading: "おたく", meaning: "your home", type: "noun" },
  { word: "落ちる", reading: "おちる", meaning: "to fall", type: "verb" },
  { word: "おっしゃる", reading: "おっしゃる", meaning: "to say", type: "hiragana, honorific verb" },
  { word: "お祭り", reading: "おまつり", meaning: "festival", type: "noun" },
  { word: "お見舞い", reading: "おみまい", meaning: "visiting someone ill", type: "noun" },
  { word: "お土産", reading: "おみやげ", meaning: "souvenir", type: "noun" },
  { word: "お湯", reading: "おゆ", meaning: "hot water", type: "noun" },
  { word: "下りる", reading: "おりる", meaning: "to get off, to descend", type: "verb" },
  { word: "折る", reading: "おる", meaning: "to fold, to break", type: "verb" },
  { word: "終わり", reading: "おわり", meaning: "the end", type: "noun" },
  { word: "会場", reading: "かいじょう", meaning: "venue, meeting place", type: "noun" },
  { word: "会話", reading: "かいわ", meaning: "conversation", type: "noun, suru verb" },
  { word: "帰り", reading: "かえり", meaning: "return, way home", type: "noun" },
  { word: "科学", reading: "かがく", meaning: "science", type: "noun" },
  { word: "鏡", reading: "かがみ", meaning: "mirror", type: "noun" },
  { word: "係", reading: "かかり", meaning: "person in charge", type: "noun" },
  { word: "掛ける", reading: "かける", meaning: "to hang, to call, to spend", type: "verb" },
  { word: "飾る", reading: "かざる", meaning: "to decorate", type: "verb" },
  { word: "火事", reading: "かじ", meaning: "fire", type: "noun" },
  { word: "ガス", reading: "ガス", meaning: "gas", type: "katakana, noun" },
  { word: "ガソリン", reading: "ガソリン", meaning: "gasoline", type: "katakana, noun" },
  { word: "固い", reading: "かたい", meaning: "hard, solid", type: "i-adjective" },
  { word: "形", reading: "かたち", meaning: "shape, form", type: "noun" },
  { word: "片付ける", reading: "かたづける", meaning: "to tidy up", type: "verb" },
  { word: "課長", reading: "かちょう", meaning: "section manager", type: "noun" },
  { word: "勝つ", reading: "かつ", meaning: "to win", type: "verb" },
  { word: "角", reading: "かど", meaning: "corner", type: "noun" },
  { word: "家内", reading: "かない", meaning: "one's wife", type: "noun" },
  { word: "悲しい", reading: "かなしい", meaning: "sad", type: "i-adjective" },
  { word: "必ず", reading: "かならず", meaning: "without fail", type: "adverb" },
  { word: "壁", reading: "かべ", meaning: "wall", type: "noun" },
  { word: "構う", reading: "かまう", meaning: "to mind, to care about", type: "verb" },
  { word: "髪", reading: "かみ", meaning: "hair", type: "noun" },
  { word: "噛む", reading: "かむ", meaning: "to bite, to chew", type: "verb" },
  { word: "通う", reading: "かよう", meaning: "to commute, to attend", type: "verb" },
  { word: "ガラス", reading: "ガラス", meaning: "glass", type: "katakana, noun" },
  { word: "彼", reading: "かれ", meaning: "he, boyfriend", type: "pronoun" },
  { word: "彼女", reading: "かのじょ", meaning: "she, girlfriend", type: "pronoun" },
  { word: "乾く", reading: "かわく", meaning: "to dry", type: "verb" },
  { word: "代わり", reading: "かわり", meaning: "substitute, replacement", type: "noun" },
  { word: "考える", reading: "かんがえる", meaning: "to think, to consider", type: "verb" },
  { word: "看護師", reading: "かんごし", meaning: "nurse", type: "noun" },
  { word: "簡単", reading: "かんたん", meaning: "simple, easy", type: "na-adjective" },
  { word: "機会", reading: "きかい", meaning: "opportunity", type: "noun" },
  { word: "危険", reading: "きけん", meaning: "danger", type: "na-adjective" },
  { word: "聞こえる", reading: "きこえる", meaning: "to be audible", type: "verb" },
  { word: "決まる", reading: "きまる", meaning: "to be decided", type: "verb" },
  { word: "気持ち", reading: "きもち", meaning: "feeling", type: "noun" },
  { word: "君", reading: "きみ", meaning: "you", type: "pronoun" },
  { word: "決める", reading: "きめる", meaning: "to decide", type: "verb" },
  { word: "気分", reading: "きぶん", meaning: "mood, feeling", type: "noun" },
  { word: "着物", reading: "きもの", meaning: "kimono", type: "noun" },
  { word: "客", reading: "きゃく", meaning: "guest, customer", type: "noun" },
  { word: "急行", reading: "きゅうこう", meaning: "express train", type: "noun" },
  { word: "教育", reading: "きょういく", meaning: "education", type: "noun" },
  { word: "教会", reading: "きょうかい", meaning: "church", type: "noun" },
  { word: "競争", reading: "きょうそう", meaning: "competition", type: "noun, suru verb" },
  { word: "興味", reading: "きょうみ", meaning: "interest", type: "noun" },
  { word: "近所", reading: "きんじょ", meaning: "neighborhood", type: "noun" },
  { word: "空気", reading: "くうき", meaning: "air, atmosphere", type: "noun" },
  { word: "空港", reading: "くうこう", meaning: "airport", type: "noun" },
  { word: "草", reading: "くさ", meaning: "grass", type: "noun" },
  { word: "首", reading: "くび", meaning: "neck", type: "noun" },
  { word: "雲", reading: "くも", meaning: "cloud", type: "noun" },
  { word: "比べる", reading: "くらべる", meaning: "to compare", type: "verb" },
  { word: "暮れる", reading: "くれる", meaning: "to get dark", type: "verb" },
  { word: "くれる", reading: "くれる", meaning: "to give me", type: "hiragana, verb" },
  { word: "計画", reading: "けいかく", meaning: "plan", type: "noun, suru verb" },
  { word: "警察", reading: "けいさつ", meaning: "police", type: "noun" },
  { word: "経験", reading: "けいけん", meaning: "experience", type: "noun, suru verb" },
  { word: "ケーキ", reading: "ケーキ", meaning: "cake", type: "katakana, noun" },
  { word: "ゲーム", reading: "ゲーム", meaning: "game", type: "katakana, noun" },
  { word: "コンピューター", reading: "コンピューター", meaning: "computer", type: "katakana, noun" },
  { word: "サラダ", reading: "サラダ", meaning: "salad", type: "katakana, noun" },
  { word: "サンダル", reading: "サンダル", meaning: "sandals", type: "katakana, noun" },
  { word: "スーツ", reading: "スーツ", meaning: "suit", type: "katakana, noun" },
  { word: "ステーキ", reading: "ステーキ", meaning: "steak", type: "katakana, noun" },
  { word: "テキスト", reading: "テキスト", meaning: "textbook", type: "katakana, noun" },
  { word: "パソコン", reading: "パソコン", meaning: "personal computer", type: "katakana, noun" },
  { word: "プレゼント", reading: "プレゼント", meaning: "present, gift", type: "katakana, noun" },
  { word: "しばらく", reading: "しばらく", meaning: "for a while", type: "hiragana, adverb" },
  { word: "ずっと", reading: "ずっと", meaning: "continuously, much more", type: "hiragana, adverb" },
  { word: "たいてい", reading: "たいてい", meaning: "usually, mostly", type: "hiragana, adverb" },
  { word: "だめ", reading: "だめ", meaning: "no good, useless", type: "hiragana, na-adjective" },
  { word: "ちゃん", reading: "ちゃん", meaning: "suffix for children or close people", type: "hiragana, suffix" },
  { word: "どんどん", reading: "どんどん", meaning: "rapidly, steadily", type: "hiragana, adverb" },
  { word: "はっきり", reading: "はっきり", meaning: "clearly", type: "hiragana, adverb" },
  { word: "びっくり", reading: "びっくり", meaning: "surprise", type: "hiragana, suru verb" },
  { word: "ほとんど", reading: "ほとんど", meaning: "almost, hardly", type: "hiragana, adverb" },
  { word: "もっと", reading: "もっと", meaning: "more", type: "hiragana, adverb" }
];
